version: "3.3"

services:
    client:
        container_name: "client"
        build: ./client/
        stdin_open: true
        ports:
            - "3000:3000"
        depends_on:
            - server
        networks:
            - app-network

    server:
        container_name: "server"
        build: ./server/
        ports:
            - "5000:5000"
        environment:
            PORT: 5000
            DB_URL: "mysql://user:123123@db:3306/etracker_db?charset=UTF8"
            JWT_SECRET: "super-secret-key"
            EMAIL_ADDRESS: "email@email.com"
            EMAIL_PASSWORD: "email_password"
            FORGOT_PASSWORD_LINK: "http://localhost:3000"
            WAIT_HOSTS: db:3306
            MYSQL_HOST: db
        depends_on:
            - db
        networks:
            - app-network

    db:
        image: "mysql/mysql-server:latest-aarch64"
        container_name: "db"
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: "etracker_db"
            MYSQL_ROOT_PASSWORD: "123123"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "123123"
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - "3306:3306"
        expose:
            # Opens port 3306 on the container
            - "3306"
        # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        tty: true
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
# Names our volume
volumes:
    my-db:
